/*
 * Copyright (c) 2026 Julian Zander <zanderjulian@gmx.de>
 *                    Jonas Schaub <jonas.schaub@uni-jena.de>
 *                    Achim Zielesny <achim.zielesny@w-hs.de>
 *                    Christoph Steinbeck <christoph.steinbeck@uni-jena.de>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */

plugins {
    id 'application'
    id 'org.gradle.java'
    id 'jacoco'
    id 'java-library'
    id 'java'
    id "com.diffplug.spotless" version "8.9.0"
    id "com.vanniktech.maven.publish" version "0.35.0"
    id "org.sonarqube" version "7.1.0.6387"
}

group = 'io.github.jonasschaub'
//see also version for publishing below! And do not forget to update CITATION.cff version as well!!!
version = '1.1.0'

base {
    archivesName = 'scaffold-graph-vis'
}

javadoc {
    if (JavaVersion.current().isJava9Compatible()) {
        options.addBooleanOption('html5', true)
    }
    options.addStringOption('Xdoclint:none', '-quiet')
    failOnError = false
}

repositories {
    mavenCentral()
}

def graphStreamVersion = '2.0'
dependencies {
    implementation "org.jetbrains:annotations:26.1.0"
    implementation "org.graphstream:gs-core:${graphStreamVersion}"
    implementation "org.graphstream:gs-ui-swing:${graphStreamVersion}"
    implementation "org.graphstream:gs-ui-javafx:${graphStreamVersion}"
    implementation "org.graphstream:gs-algo:${graphStreamVersion}"
    implementation "org.openscience.cdk:cdk-bundle:2.9"
    implementation "org.openscience.cdk:cdk-scaffold:2.9"
    testImplementation(platform('org.junit:junit-bom:6.0.1'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()

    forkEvery = 1

    testLogging {
        showStandardStreams = true
    }
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport // report is always generated after tests run
}

jacocoTestReport {
    reports {
        xml.required = true
    }
    dependsOn test // tests are required to run before generating the report
}

spotless {
    java {
        encoding 'UTF-8'
        cleanthat()
        importOrder('de', 'org', 'com', 'java', 'javax')
        removeUnusedImports()
        leadingTabsToSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
        licenseHeaderFile('License-header/License-header.txt')
        //eclipse() //not optimal, because indents with tabs..
        //googleJavaFormat() //not optimal, because indents with two spaces...
        //palantirJavaFormat() //not optimal, because unnecessary line breaks in head of for loop and corrupts editor folds
        //prettier() //needs npm installed, unsuitable...
        //clangFormat() //also needs an installation...
        custom 'Refuse wildcard imports', {
            // Wildcard imports can't be resolved by spotless itself.
            // This will require the developer themselves to adhere to best practices.
            if (it =~ /\nimport .*\*;/) {
                throw new AssertionError("Do not use wildcard imports. 'spotlessApply' cannot resolve this issue.")
            }
        }
    }
}

sonar {
    properties {
        property("sonar.projectKey", "JonasSchaub_scaffold-graph-vis")
        property("sonar.organization", "jonasschaub")
    }
}

mavenPublishing {
    publishToMavenCentral(false, false) // automaticRelease = false, validateDeployment = false

    signAllPublications()

    coordinates("io.github.jonasschaub", "scaffold-graph-vis", "1.1.0")

    pom {
        name = 'scaffold-graph-vis'
        description = 'Basic utilities for visualising cdk-scaffold graphs using GraphStream'
        url = 'https://github.com/JonasSchaub/scaffold-graph-vis'
        inceptionYear = '2023'

        licenses {
            license {
                name = 'GNU Lesser General Public License v2.1'
                url = 'https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html'
                distribution = 'https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html'
            }
        }

        developers {
            developer {
                id = 'Julian-Z98'
                name = 'Julian Zander'
                email = 'zanderjulian@gmx'
                url = 'https://github.com/Julian-Z98'
            }
            developer {
                id = 'JonasSchaub'
                name = 'Jonas Schaub'
                email = 'jonas.schaub@uni-jena.de'
                url = 'https://github.com/JonasSchaub'
            }
            developer {
                name = 'Achim Zielesny'
                email = 'achim.zielesny@w-hs.de'
                url = 'https://www.w-hs.de/service/informationen-zur-person/person/zielesny'
            }
            developer {
                name = 'Christoph Steinbeck'
                email = 'christoph.steinbeck@uni-jena.de'
                url = 'https://cheminf.uni-jena.de/members/steinbeck'
            }
        }

        scm {
            connection = 'scm:git:git://github.com/JonasSchaub/scaffold-graph-vis.git'
            developerConnection = 'scm:git:ssh://github.com/JonasSchaub/scaffold-graph-vis.git'
            url = 'https://github.com/JonasSchaub/scaffold-graph-vis/'
        }
    }
}

tasks.matching { it.name == 'generateMetadataFileForMavenPublication' }.configureEach {
    dependsOn 'plainJavadocJar'
}
